#!/usr/bin/env python3
"""List every post file so the website can discover it.

The site reads posts straight from the content folders:

    research/*.md     data-lab/*.md     resources/*.md

A browser cannot list a folder on a static host, so this script writes
content-manifest.json — just the list of file paths. Nothing else needs editing.

    python tools/build_content.py     # run before deploying (or as the host's build command)

tools/serve.py regenerates the manifest on every request, so during local
development a new file appears as soon as the page is refreshed.
Files whose names start with "_" (such as _template.md) are ignored.
"""
import datetime
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FOLDERS = ('research', 'data-lab', 'resources')
MANIFEST = os.path.join(ROOT, 'content-manifest.json')
BUNDLE = os.path.join(ROOT, 'assets', 'js', 'content-bundle.js')


def collect():
    files = []
    for folder in FOLDERS:
        path = os.path.join(ROOT, folder)
        if not os.path.isdir(path):
            continue
        for name in sorted(os.listdir(path)):
            if name.endswith('.md') and not name.startswith(('_', '.')):
                files.append(f'{folder}/{name}')
    return files


def build():
    return {
        'generated': datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds'),
        'folders': list(FOLDERS),
        'files': collect(),
    }


def bundle_js():
    """Every post's text in one script, so the site also works when opened as a local file."""
    posts = {}
    for path in collect():
        with open(os.path.join(ROOT, path), encoding='utf-8') as f:
            posts[path] = f.read()
    return ('/* Generated by tools/build_content.py — do not edit. */\n'
            'window.YD_BUNDLE = ' + json.dumps(posts, ensure_ascii=False) + ';\n')


def main():
    manifest = build()
    with open(MANIFEST, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2)
        f.write('\n')
    with open(BUNDLE, 'w', encoding='utf-8') as f:
        f.write(bundle_js())
    print(f'content-manifest.json: {len(manifest["files"])} posts')
    for p in manifest['files']:
        print('  ' + p)


if __name__ == '__main__':
    main()
